---
- name: Update Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NGINX
  apt:
    name: ["nginx"]
    state: latest

- name: Create www root directory
  file:
    path: /var/www/{{ domain }}
    state: directory
    mode: "0775"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Delete Default NGINX Site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Copy NGINX site.conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
