---
# ansible-playbook -e server_hosts=acg1 -e key_name=lnxa_rsa -k -K ssh_copyid.yml
- hosts: "{{ server_hosts | default('acg') }}"
  gather_facts: true
  vars:
    - sshkey: "{{ key_name }}"
  tasks:
    - name: Copy SSH Pub Key to Remote Server
      ansible.posix.authorized_key:
        user: "{{ ansible_env.USER }}"
        state: present
        key: "{{ item }}"
      with_file:
        - "{{ lookup('env', 'HOME') }}/.ssh/{{ sshkey }}.pub"

    - name: allow "{{ ansible_env.USER }}" to have passwordless sudo
      become: yes
      lineinfile:
        create: yes
        dest: /etc/sudoers.d/{{ ansible_env.USER }}
        line: '{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

