---
- hosts: localhost
  vars:
    - sshkey: "{{ key_name }}"
  tasks:
    - name: Generate Key pair
      community.crypto.openssh_keypair:
        path: "{{ lookup('env', 'HOME') }}/.ssh/{{ sshkey }}"
        comment: SSHkey_for_Ansible
