---
- name: Reading unseal key contents
  delegate_to: localhost
  connection: local
  shell: "cat {{ unseal_keys_dir_output }}/unseal_keys"
  register: keyslist

- name: Read Threshold (3) keys to unseal the vault
  command: "vault operator unseal {{ item.1 }}"
  with_indexed_items: "{{ keyslist.stdout_lines }}"
  when: item.0 < 3
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
