#################################################
# Playbook to install Docker and other things
#################################################
---
- hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Create {{ users }} user
      user: 
        name: "{{ user }}"
        state: present 
      loop: "{{ users }}"
      loop_control:
        loop_var: user

    - name: allow {{ users }} to have passwordless sudo
      lineinfile:
        create: yes
        dest: /etc/sudoers.d/{{ user }}
        line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      loop: "{{ users }}"
      loop_control:
        loop_var: user

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo:  deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce-cli {{ docker_version }}
      apt: update_cache=yes name=docker-ce-cli={{ docker_version }} state=present

    - name: Update apt and install docker-ce {{ docker_version }}
      apt: update_cache=yes name=docker-ce={{ docker_version }} state=present

    - name: Install containerd.io
      apt: name=containerd.io state=present
