---
# export ANSIBLE_CONFIG=/tmp/ansible.cfg
# ansible-playbook -e server_hosts=la2 main.yml
#
- hosts: "{{ server_hosts }}"
  roles:
    - { role: acg, tags: [acg]}
    - { role: docker, become: yes, tags: [docker]}
    - { role: vault, become: yes, tags: [vault] }
    - { role: nginx, become: yes, tags: [nginx] }
  any_errors_fatal: true
